name: Continuous Integration

on:
  push:
    branches: [main]

jobs:
  ci:
    name: CI - Test, Lint, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint
        continue-on-error: false

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Report Success
        if: success()
        run: echo "✅ All checks passed successfully!"

      - name: Report Failure
        if: failure()
        run: echo "❌ Some checks failed. Please review the logs above."
