name: Build and Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - run: npm install
      - run: npm run lint:ci
      - run: npm test
      - run: npm run docs:build
      
      - name: Show build success
        run: echo "Build completed successfully - Enable GitHub Pages in settings to deploy"
