name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Generate documentation site
      - name: Build docs
        run: |
          mkdir -p docs-site
          
          # Create simple docs page
          cat > docs-site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Heavens Above - Docs</title>
              <style>
                  body { 
                      font-family: Arial, sans-serif; 
                      max-width: 1000px; 
                      margin: 50px auto; 
                      padding: 20px;
                  }
                  h1 { color: #333; }
                  .section { 
                      background: #f5f5f5; 
                      padding: 20px; 
                      margin: 20px 0; 
                      border-radius: 5px;
                  }
              </style>
          </head>
          <body>
              <h1>Heavens Above Documentation</h1>
              <p>Automated documentation for the Heavens Above project</p>
              
              <div class="section">
                  <h2>Available Workflows</h2>
                  <ul>
                      <li>CI - Continuous Integration</li>
                      <li>Deploy - Deployment Pipeline</li>
                      <li>Scheduled Maintenance</li>
                      <li>Dependency Updates</li>
                      <li>PR Checks</li>
                      <li>Documentation Deployment</li>
                      <li>Release & Analytics</li>
                  </ul>
              </div>
              
              <div class="section">
                  <h2>Links</h2>
                  <p><a href="https://github.com/MUNEEBAZAM96/heavens-above_SCD_Assignment_2">Repository</a></p>
                  <p><a href="https://muneebazam96.github.io/heavens-above_SCD_Assignment_2/">Live Site</a></p>
              </div>
          </body>
          </html>
          EOF

      # Save docs as artifact
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs-site/
          retention-days: 90

      - run: echo "Documentation built and saved"
