name: Documentation Deployment

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'package.json'
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    name: Build Documentation
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build documentation
        run: npm run docs:build
        
      - name: Validate documentation structure
        run: |
          if [ -d "docs/build" ]; then
            echo "Documentation built successfully"
            ls -la docs/build/
          else
            echo "Documentation build directory not found"
            exit 1
          fi

  deploy-pages:
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    needs: build-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Build documentation
        run: |
          npm ci
          npm run docs:build
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  versioned-docs:
    runs-on: ubuntu-latest
    name: Versioned Documentation
    if: github.event_name == 'release'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Extract version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Build versioned docs
        run: |
          npm ci
          npm run docs:build
          mkdir -p docs/versions
          cp -r docs/build docs/versions/${{ steps.version.outputs.version }}

  docs-health-check:
    runs-on: ubuntu-latest
    name: Documentation Health Check
    needs: deploy-pages
    
    steps:
      - name: Check documentation accessibility
        run: |
          if [ -n "${{ needs.deploy-pages.outputs.page_url }}" ]; then
            curl -f ${{ needs.deploy-pages.outputs.page_url }} || echo "Documentation not yet accessible"
          fi
          
      - name: Verify build artifacts
        run: |
          [ -d "docs/build" ] && echo "Build artifacts present" || echo "No build artifacts"
